import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Rocket, Bot, Loader2, Check, Play, Send, ArrowRight, BriefcaseBusiness, MessageSquareMore, Wand2 } from "lucide-react";
import { useStudioContext } from "@/context/StudioContext";
import { api } from "@/lib/api";
import { findGameTemplate } from "@/lib/templates-loader";
import { engineOf, getThumbnailUrl, templateEmoji } from "@/lib/studio-meta";
import { sendZeroGGenerationPayment } from "@/lib/zeroGPayment";
import { CreatePageSkeleton } from "@/components/studio/PageSkeletons";
import profileBg from "@/assets/profile-bg.png";
import cyberpunkSuggestion from "@/assets/create-suggestion-cyberpunk.png";
import farmSuggestion from "@/assets/create-suggestion-farm.png";

export const Route = createFileRoute("/_app/create")({
  pendingComponent: CreatePageSkeleton,
  head: () => ({
    meta: [
      { title: "Create — Creator Studio" },
      { name: "description", content: "Describe your game in a prompt and let the agent build a playable version." },
    ],
  }),
  component: Create,
});

const ideas: Array<{ icon: string; text: string; image?: string }> = [
  { icon: "🏙️", image: cyberpunkSuggestion, text: "A neon-cyberpunk parkour runner in Tokyo" },
  { icon: "🐾", image: farmSuggestion, text: "Cozy farm sim where animals talk back" },
  { icon: "🪐", text: "Voxel space pirate adventure" },
  { icon: "🐱", text: "Roguelike dungeon crawler with cats" },
  { icon: "🥋", text: "Tekken style martial arts fighter generated by the AI agent" },
];

const vibeIdeas = ["Chill vibes", "World Cup energy", "Neon arcade", "Kids friendly"];

const steps = ["Submitting prompt", "Writing game code", "Testing & repairing", "Playable build ready"];

// Maps the backend job's real progress stage to a step above — no more
// timer-faked progress. Unknown/absent stage means the job hasn't streamed
// its first progress report yet.
const stageToStep: Record<string, number> = {
  "writing-code": 1,
  "editing-seed": 1,
  "repairing": 2,
  "fixing-syntax": 2,
  "fixing-runtime": 2,
};

type ChatMessage = {
  role: "assistant" | "user";
  text: string;
};

type ChatStage = "game" | "vibe" | "concept" | "ready";

const conceptByGame: Record<string, string[]> = {
  fruit: [
    "Fruit Slice Zen: Swipe through flying fruit, avoid bombs, chain combos, and keep the pace calm but satisfying.",
    "Fruit Ninja Arcade: A fast slicing game with fruit arcs, combo streaks, bombs to avoid, and juicy touch controls.",
  ],
  chess: [
    "Royal Gambit: A calm 1-on-1 chess match against a thoughtful AI on a clean neon board.",
    "Knight's Duel: Sharp tactical chess with highlighted legal moves and quick AI replies.",
  ],
  soccer: [
    "World Cup Rush: A fast arcade soccer match with quick goals, dramatic saves, and bright stadium energy.",
    "Street Header: A playful head-soccer duel in a neon street arena with bouncy physics.",
  ],
  runner: [
    "River Ripple: Guide a calm lily pad through a winding river, collecting blossoms and avoiding leaves.",
    "Dream Dash: Run through a soft pastel skyline, collecting stars and gliding past gentle obstacles.",
  ],
  racing: [
    "Mini Traffic Drift: Weave through traffic, collect boost pickups, and chase the cleanest lap.",
    "Sunset Sprint: A chill top-down racer with warm roads, smooth turns, and simple mobile controls.",
  ],
  bubble: [
    "Bubble Reef: Aim colorful bubbles through a peaceful underwater board with satisfying pops.",
    "Cloud Popper: Clear floating bubble clusters in a soft sky world.",
  ],
  match: [
    "Block Bloom: Swap colorful blocks to grow combos in a cozy puzzle garden.",
    "Gem Picnic: A bright match-3 board with relaxed scoring and cheerful effects.",
  ],
};

function gameKind(text: string) {
  const value = text.toLowerCase();
  if (/(fruit\s*ninja|fruit|slice|slicing|slash|knife|blade)/.test(value)) return "fruit";
  if (/(chess|checkmate|chessboard)/.test(value)) return "chess";
  if (/(soccer|football|world cup)/.test(value)) return "soccer";
  if (/(runner|running|run|parkour|jump)/.test(value)) return "runner";
  if (/(racing|racer|race|car|driv)/.test(value)) return "racing";
  if (/(bubble|shooter|aim)/.test(value)) return "bubble";
  if (/(match|blocks|jewel|candy)/.test(value)) return "match";
  return "runner";
}

function conceptFor(game: string, vibe: string) {
  const [first, fallback] = conceptByGame[game] ?? conceptByGame.runner;
  if (/chill|calm|cozy|peace|soft|relax/i.test(vibe)) return first;
  return fallback ?? first;
}

// Asks the real background agent for a concept. Returns null on any failure so
// the caller can fall back to the canned conceptFor() list.
async function fetchConceptFromAgent(gameIdea: string, vibe: string): Promise<string | null> {
  try {
    const { data } = await api.post(
      "/agents/background",
      {
        task: "game-concept",
        input: {
          instruction:
            "Write ONE original browser mini-game concept for the given game idea and vibe. Reply with a single line of plain text, no markdown, formatted exactly as '<Catchy Title>: <two short sentences describing the playable mechanics and mood>'. Under 60 words.",
          gameIdea,
          vibe,
        },
      },
      { timeout: 45000 },
    );
    const text = String(data?.result?.content ?? "").trim().replace(/^["'`]+|["'`]+$/g, "");
    if (!/^[^:\n]{2,60}:\s.+/s.test(text)) return null;
    return text.split("\n")[0].trim();
  } catch {
    return null;
  }
}

function isCreateConfirmation(text: string) {
  return /^(ok|okay|yes|yep|sure|create it|build it|go ahead|start)(,?\s+)?(create|build|make|start)?\s*(it)?!?$/i.test(
    text.trim(),
  );
}

function Create() {
  const { studio, addCreatedGame, removeCreatedGame } = useStudioContext();
  const navigate = useNavigate();
  const [templateSeed, setTemplateSeed] = useState<any | null>(null);
  const [chatStage, setChatStage] = useState<ChatStage>("game");
  const [chatInput, setChatInput] = useState("");
  const [gameRequest, setGameRequest] = useState("");
  const [vibeRequest, setVibeRequest] = useState("");
  const [selectedConcept, setSelectedConcept] = useState("");
  // The confirmed prompt, waiting for the user to pick a strategy. Nothing
  // builds until one of the two mode buttons is clicked.
  const [finalPrompt, setFinalPrompt] = useState("");
  const [generationNotice, setGenerationNotice] = useState("");
  const [isPaying, setIsPaying] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([
    { role: "assistant", text: "Hey there! What kind of game do you want to create?" },
  ]);

  // The build itself lives in studio state + localStorage (kult-active-build),
  // so it survives navigating away and full page refreshes. This page only
  // renders whatever build is active until the user cancels/dismisses it.
  const activeBuild = studio.activeBuild;
  const phase: "idle" | "building" | "done" | "failed" = activeBuild ? activeBuild.phase : "idle";
  const buildingStrategy = phase === "building" ? activeBuild!.strategy : null;
  const builtGame = activeBuild?.game ?? null;
  // Re-render once a second while building so the elapsed time and step list move
  // even between 5s job polls.
  const [, setTick] = useState(0);
  useEffect(() => {
    const templateId = sessionStorage.getItem("kult-create-template-id");
    if (templateId) {
      sessionStorage.removeItem("kult-create-template-id");
      void findGameTemplate(templateId).then((template) => {
        if (!template) return;
        setTemplateSeed(template);
        studio.setEngine(engineOf(template));
        studio.setSelectedId(template.id);
        const category = String(template.category ?? "arcade").toLowerCase();
        const basePrompt = `Create a game like ${template.name}. Keep the core ${category} template feel: ${template.mechanic}`;
        setGameRequest(basePrompt);
        setChatStage("vibe");
        setMessages([
          {
            role: "assistant",
            text: `${template.name} is selected as your template. Tell me what theme, characters, rules, or difficulty changes you want.`,
          },
          { role: "user", text: basePrompt },
        ]);
        studio.setPrompt(basePrompt);
      });
      return;
    }

    const remixPrompt = sessionStorage.getItem("kult-remix-prompt");
    if (remixPrompt) {
      sessionStorage.removeItem("kult-remix-prompt");
      setGameRequest(remixPrompt);
      setChatStage("vibe");
      setMessages([
        { role: "assistant", text: "Remix loaded. What theme or character swap do you want?" },
        { role: "user", text: remixPrompt },
      ]);
      studio.setPrompt(remixPrompt);
      return;
    }

    const heroPrompt = sessionStorage.getItem("kult-create-prompt");
    if (heroPrompt) {
      sessionStorage.removeItem("kult-create-prompt");
      setChatInput(heroPrompt);
    }
  }, [studio]);

  useEffect(() => {
    if (phase !== "building") return;
    const interval = setInterval(() => setTick((t) => t + 1), 1000);
    return () => clearInterval(interval);
  }, [phase]);
  const elapsedSec = activeBuild ? Math.max(0, Math.floor((Date.now() - activeBuild.startedAt) / 1000)) : 0;
  const step =
    phase === "building"
      ? stageToStep[activeBuild?.progressStage ?? ""] ?? 0
      : steps.length - 1;

  // What the user told the chat so far ("create a snake game. Chill vibes").
  // The strategy buttons must build THAT, not the stale studio.prompt default —
  // chat only writes studio.prompt at the final "Ok, create it!" step.
  const chatPrompt = [gameRequest, vibeRequest].filter(Boolean).join(". ");

  const build = async (strategy: "pure-agent" | "hybrid", promptOverride = "") => {
    const pendingInput = chatInput.trim();
    const promptWithPendingInput = [finalPrompt || chatPrompt || studio.prompt, pendingInput]
      .filter(Boolean)
      .join(". ");
    const buildPrompt = promptOverride || promptWithPendingInput;
    if (!buildPrompt.trim() || phase === "building") return;
    setGenerationNotice("");
    try {
      const game = await studio.generateFromPrompt(strategy, buildPrompt);
      if (game) addCreatedGame(game);
    } catch (error: any) {
      const payment = error?.response?.data?.payment;
      if (error?.response?.status === 402 && payment) {
        const amount = payment.amount ?? 2;
        const currency = payment.currency ?? "0G";
        try {
          setIsPaying(true);
          setGenerationNotice(`Confirm ${amount} ${currency} in your wallet to generate another game.`);
          const paymentTxHash = await sendZeroGGenerationPayment(amount);
          setGenerationNotice("Payment sent. Verifying on 0G mainnet...");
          const game = await studio.generateFromPrompt(strategy, buildPrompt, paymentTxHash);
          if (game) addCreatedGame(game);
          setGenerationNotice("");
        } catch (paymentError: any) {
          setGenerationNotice(paymentError?.response?.data?.error ?? paymentError?.message ?? `Could not complete ${currency} payment.`);
        } finally {
          setIsPaying(false);
        }
      } else {
        setGenerationNotice(error?.response?.data?.error ?? error?.message ?? "Could not start generation.");
      }
    }
  };

  // Cancel a running build: stop polling, drop the persisted record, and delete
  // the already-saved game entry so nothing half-built lingers in My Creations.
  const cancelBuild = () => {
    const gameId = activeBuild?.game?.id;
    studio.cancelActiveBuild();
    if (phase === "building" && gameId) void removeCreatedGame(gameId);
  };

  const sendChat = (text = chatInput) => {
    const value = text.trim();
    if (!value || phase === "building") return;
    setChatInput("");

    if (chatStage === "game") {
      setGameRequest(value);
      setChatStage("vibe");
      setMessages((current) => [
        ...current,
        { role: "user", text: value },
        {
          role: "assistant",
          text: `Awesome! ${value} games are super fun. Do you have any specific vibes in mind, or should I throw out some ideas?`,
        },
      ]);
      return;
    }

    if (chatStage === "vibe") {
      const game = gameKind(gameRequest || value);
      setVibeRequest(value);
      setChatStage("concept");
      setMessages((current) => [
        ...current,
        { role: "user", text: value },
        { role: "assistant", text: `Perfect choice. Cooking up a ${value} concept…` },
      ]);
      // Real concept from the background agent; canned list only as fallback
      // when the backend or model is unreachable.
      void (async () => {
        const concept =
          (await fetchConceptFromAgent(gameRequest || value, value)) ?? conceptFor(game, value);
        setSelectedConcept(concept);
        setMessages((current) => [
          ...current,
          { role: "assistant", text: concept },
          {
            role: "assistant",
            text: "Say “Ok, create it!” to lock this concept in, then pick Hybrid Mode or Pure Agent Strategy to build it.",
          },
        ]);
      })();
      return;
    }

    if (chatStage === "concept") {
      const extraPrompt = isCreateConfirmation(value) ? "" : value;
      const prompt = [gameRequest, vibeRequest, selectedConcept, extraPrompt].filter(Boolean).join(". ");
      studio.setPrompt(prompt);
      setFinalPrompt(prompt);
      setChatStage("ready");
      setMessages((current) => [
        ...current,
        { role: "user", text: value },
        {
          role: "assistant",
          text: `Plan ready for ${selectedConcept.split(":")[0]}! Choose Hybrid Mode or Pure Agent Strategy below to start building.`,
        },
      ]);
    }
  };

  const submitComposerPrompt = () => {
    const value = chatInput.trim();
    if (!value || phase === "building") return;

    if (chatStage === "concept" && isCreateConfirmation(value)) {
      sendChat(value);
      return;
    }

    const prompt = [gameRequest, vibeRequest, selectedConcept, value].filter(Boolean).join(". ");
    studio.setPrompt(prompt);
    setFinalPrompt(prompt);
    setChatInput("");
    setChatStage("ready");
    setMessages((current) => [
      ...current,
      { role: "user", text: value },
      {
        role: "assistant",
        text: "Got it — that's your prompt. Choose Hybrid Mode or Pure Agent Strategy below to start building.",
      },
    ]);
  };

  const freshChat = chatStage === "game" && messages.length <= 1;

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#d9b2ff] text-white">
      <img
        src={profileBg}
        alt=""
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 z-0 h-full w-full object-cover object-top"
      />
      <div className="absolute inset-0 z-0 bg-[radial-gradient(circle_at_50%_0%,rgba(255,255,255,0.35),transparent_28%),linear-gradient(180deg,rgba(255,255,255,0.08),rgba(126,34,206,0.18))]" />

      <div className="relative z-10 mx-auto max-w-3xl px-4 pb-28 pt-4 sm:px-6 lg:pb-6">
        <header className="mb-5 flex items-center justify-between gap-3">
          <div className="flex min-w-0 items-center gap-3 rounded-[1.6rem] border-2 border-white/70 bg-white/72 px-3.5 py-2.5 text-violet-950 shadow-[0_0_0_2px_rgba(168,85,247,0.22),0_0_28px_rgba(168,85,247,0.45),inset_0_2px_12px_rgba(255,255,255,0.95)] backdrop-blur">
            <span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[linear-gradient(135deg,#a855f7,#ec4899)] text-white shadow-[0_8px_16px_rgba(168,85,247,0.34)]">
              <MessageSquareMore className="size-6" />
            </span>
            <div className="font-display text-2xl font-black leading-none text-violet-800 drop-shadow-[0_2px_0_rgba(255,255,255,0.8)] sm:text-3xl">
              CREATE
              <span className="block">WITH CHAT</span>
            </div>
          </div>
          <span className="hidden shrink-0 items-center gap-2 rounded-[1.6rem] border-2 border-violet-300/60 bg-white/72 px-4 py-3 font-display text-sm font-black text-violet-800 shadow-[inset_0_2px_10px_rgba(255,255,255,0.9),0_0_18px_rgba(168,85,247,0.3)] backdrop-blur sm:flex">
            <Bot className="size-6 text-violet-700" /> AI Game Studio
          </span>
        </header>

        {templateSeed && (
          <div className="mb-4 flex gap-3 rounded-[1.5rem] border-2 border-fuchsia-200 bg-white/80 p-3 text-violet-950 shadow-[0_0_18px_rgba(168,85,247,0.3)] backdrop-blur">
            <div className="relative size-16 shrink-0 overflow-hidden rounded-2xl border border-violet-200 bg-violet-100">
              {getThumbnailUrl(templateSeed.id) ? (
                <img src={getThumbnailUrl(templateSeed.id)} alt="" className="h-full w-full object-cover" />
              ) : (
                <span className="grid h-full place-items-center text-3xl">{templateEmoji[templateSeed.id] ?? "🎮"}</span>
              )}
            </div>
            <div className="min-w-0 flex-1">
              <p className="text-[10px] font-black uppercase tracking-[0.16em] text-fuchsia-600">Template selected</p>
              <h2 className="truncate font-display text-lg font-black">{templateSeed.name}</h2>
              <p className="line-clamp-2 text-xs font-semibold text-violet-700">{templateSeed.mechanic}</p>
            </div>
            <button
              type="button"
              onClick={() => navigate({ to: "/templates" })}
              className="self-center rounded-xl border border-violet-300 bg-white/80 px-3 py-2 text-xs font-black text-violet-700"
            >
              Change
            </button>
          </div>
        )}

        <section className="overflow-hidden rounded-[2rem] border-[5px] border-white/80 bg-[radial-gradient(circle_at_50%_5%,rgba(168,85,247,0.28),transparent_24%),linear-gradient(180deg,#160543,#070018)] p-5 shadow-[0_0_0_2px_rgba(168,85,247,0.5),0_0_36px_rgba(168,85,247,0.75),inset_0_1px_22px_rgba(255,255,255,0.12)]">
          <div className="flex flex-col items-center text-center">
            <span className="relative grid size-20 place-items-center rounded-full border-2 border-fuchsia-200 bg-[radial-gradient(circle_at_35%_25%,#ffb7ff,#a855f7_48%,#3b0764_100%)] shadow-[0_0_26px_rgba(217,70,239,0.9)]">
              <Bot className="size-11 text-cyan-200 drop-shadow-[0_0_10px_rgba(103,232,249,0.95)]" />
            </span>
            <h1 className="mt-4 font-display text-4xl font-black">Hey there! 👋</h1>
            <p className="mt-1 text-base font-bold text-violet-200">What kind of game do you want to create?</p>
          </div>

          {freshChat ? (
            <div className="mt-5 grid gap-3">
              {ideas.slice(0, 2).map((idea) => (
                <button
                  key={idea.text}
                  onClick={() => sendChat(idea.text)}
                  className="group flex items-center gap-3 rounded-[1.35rem] border border-fuchsia-300/45 bg-[linear-gradient(135deg,rgba(72,20,137,0.92),rgba(38,10,91,0.96))] p-2.5 text-left shadow-[0_0_14px_rgba(168,85,247,0.28),inset_0_1px_12px_rgba(255,255,255,0.08)] transition hover:border-fuchsia-200"
                >
                  <span className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-2xl border border-fuchsia-200/50 bg-[radial-gradient(circle,#c084fc,#4c1d95_74%)] text-3xl shadow-[inset_0_2px_10px_rgba(255,255,255,0.22)]">
                    {idea.image ? (
                      <img src={idea.image} alt="" className="h-full w-full object-cover" loading="lazy" />
                    ) : (
                      idea.icon
                    )}
                  </span>
                  <span className="min-w-0 flex-1 text-lg font-black leading-tight text-white">{idea.text}</span>
                  <ArrowRight className="size-7 shrink-0 text-fuchsia-300 transition group-hover:translate-x-1" />
                </button>
              ))}
            </div>
          ) : (
            <>
              <div className="mt-5 max-h-[36vh] space-y-3 overflow-y-auto pr-1 [scrollbar-width:thin] [scrollbar-color:rgba(232,121,249,0.75)_transparent]">
                {messages.map((message, index) => (
                  <div key={`${message.role}-${index}`} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}>
                    <div
                      className={`max-w-[86%] rounded-2xl px-4 py-3 text-sm font-semibold leading-relaxed ${
                        message.role === "user"
                          ? "bg-fuchsia-400/35 text-white"
                          : "bg-white/8 text-violet-100"
                      }`}
                    >
                      {message.text}
                    </div>
                  </div>
                ))}
              </div>
              <div className="mt-4 flex flex-wrap gap-2">
                {(chatStage === "game" ? ideas.map((i) => i.text) : vibeIdeas).map((idea) => (
                  <button
                    key={idea}
                    onClick={() => sendChat(idea)}
                    className="rounded-full border border-fuchsia-300/40 bg-white/8 px-4 py-2 text-xs font-bold text-violet-100 transition hover:border-fuchsia-200"
                  >
                    {idea}
                  </button>
                ))}
                {chatStage === "concept" && (
                  <button
                    onClick={() => sendChat("Ok, create it!")}
                    className="rounded-full bg-fuchsia-400 px-4 py-2 text-xs font-black text-white"
                  >
                    Ok, create it!
                  </button>
                )}
              </div>
            </>
          )}

          <div className="mt-5 flex items-center gap-2 rounded-[1.6rem] border border-fuchsia-300/35 bg-[#1a0a38]/85 p-2 pl-5 shadow-[inset_0_1px_12px_rgba(255,255,255,0.08)]">
            <input
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") submitComposerPrompt();
              }}
              placeholder={chatStage === "game" ? "Type soccer, runner, racing..." : "Type a prompt or command..."}
              className="min-w-0 flex-1 bg-transparent text-base font-bold text-white outline-none placeholder:text-violet-300/70"
            />
            <button
              type="button"
              onClick={() => submitComposerPrompt()}
              disabled={phase === "building"}
              className="grid size-14 shrink-0 place-items-center rounded-full bg-[linear-gradient(135deg,#c084fc,#ec4899)] text-white shadow-[0_0_22px_rgba(217,70,239,0.85)] transition hover:opacity-90 disabled:opacity-60"
            >
              <Send className="size-6" />
            </button>
          </div>
        </section>

        <div className="mt-5 grid gap-3 sm:grid-cols-2">
          <button
            onClick={() => build("hybrid")}
            disabled={phase === "building" || isPaying}
            className="group relative flex items-center gap-4 overflow-hidden rounded-[1.5rem] border-2 border-fuchsia-200/80 bg-[linear-gradient(135deg,#a855f7,#6d28d9)] p-4 text-left shadow-[0_0_24px_rgba(168,85,247,0.65),inset_0_1px_16px_rgba(255,255,255,0.18)] disabled:opacity-60"
          >
            <span className="grid size-16 shrink-0 place-items-center rounded-full bg-white/20">
              <Bot className="size-10 text-cyan-200" />
            </span>
            <span className="min-w-0 flex-1">
              <span className="block font-display text-2xl font-black text-white">HYBRID MODE</span>
              <span className="mt-1 block text-sm font-bold text-violet-100">
                {isPaying ? "Waiting for payment..." : buildingStrategy === "hybrid" ? "Building your game..." : "Best of both worlds."}
              </span>
            </span>
            <span className="grid size-12 shrink-0 place-items-center rounded-full border border-white/35 bg-white/12 text-white">
              {buildingStrategy === "hybrid" || isPaying ? <Loader2 className="size-5 animate-spin" /> : <ArrowRight className="size-6" />}
            </span>
          </button>

          <button
            onClick={() => build("pure-agent")}
            disabled={phase === "building" || isPaying}
            className="group flex items-center gap-4 rounded-[1.5rem] border-2 border-fuchsia-200/80 bg-[linear-gradient(135deg,#ec4899,#7e22ce)] p-4 text-left shadow-[0_0_24px_rgba(236,72,153,0.5),inset_0_1px_16px_rgba(255,255,255,0.18)] disabled:opacity-60"
          >
            <span className="grid size-16 shrink-0 place-items-center rounded-full bg-white/20">
              <BriefcaseBusiness className="size-9 text-pink-100" />
            </span>
            <span className="min-w-0 flex-1">
              <span className="block font-display text-xl font-black text-white">PURE AGENT</span>
              <span className="mt-1 block text-sm font-bold text-pink-100">
                {isPaying ? "Waiting for payment..." : buildingStrategy === "pure-agent" ? "Building your game..." : "AI handles everything."}
              </span>
            </span>
            <span className="grid size-12 shrink-0 place-items-center rounded-full border border-white/35 bg-white/12 text-white">
              {buildingStrategy === "pure-agent" || isPaying ? <Loader2 className="size-5 animate-spin" /> : <ArrowRight className="size-6" />}
            </span>
          </button>
        </div>

        {generationNotice && (
          <div className="mt-4 rounded-2xl border border-fuchsia-200/70 bg-white/85 px-4 py-3 text-sm font-black text-violet-900 shadow-[0_0_20px_rgba(168,85,247,0.35)]">
            {generationNotice}
          </div>
        )}

        {phase !== "idle" && (
          <div className="animate-float-up mt-6 rounded-2xl border border-border/60 bg-card p-6 shadow-card">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h3 className="font-display text-lg font-bold">
                  Build Console
                  {builtGame?.title ? <span className="text-muted-foreground"> · {builtGame.title}</span> : null}
                </h3>
                <p className="label-mono mt-1 text-[10px] text-muted-foreground">
                  {activeBuild?.statusText ?? studio.agentStatus}
                  {phase === "building" ? ` · ${Math.floor(elapsedSec / 60)}m ${elapsedSec % 60}s` : ""}
                </p>
              </div>
              {phase === "building" ? (
                <button
                  onClick={cancelBuild}
                  className="shrink-0 rounded-lg border border-destructive/50 px-3 py-1.5 text-[11px] font-bold uppercase tracking-wider text-destructive transition hover:bg-destructive/10"
                >
                  Cancel build
                </button>
              ) : (
                <button
                  onClick={cancelBuild}
                  className="shrink-0 rounded-lg border border-border/70 px-3 py-1.5 text-[11px] font-bold uppercase tracking-wider text-muted-foreground transition hover:bg-secondary"
                >
                  Dismiss
                </button>
              )}
            </div>
            <ul className="mt-4 space-y-3">
              {steps.map((s, i) => {
                const active = phase === "building" && i === step;
                const complete = phase === "done" || phase === "failed" || i < step;
                return (
                  <li key={s} className="flex items-center gap-3 text-sm">
                    <span className="flex size-6 items-center justify-center rounded-full border border-border/70">
                      {complete ? (
                        <Check className="size-3.5 text-[oklch(0.85_0.2_150)]" />
                      ) : active ? (
                        <Loader2 className="size-3.5 animate-spin text-primary" />
                      ) : (
                        <span className="size-1.5 rounded-full bg-muted-foreground" />
                      )}
                    </span>
                    <span className={complete || active ? "text-foreground" : "text-muted-foreground"}>{s}</span>
                  </li>
                );
              })}
            </ul>

            {phase === "failed" && (
              <div className="mt-6 rounded-xl border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
                {activeBuild?.statusText ?? "The AI build failed."}
                {builtGame?.id && activeBuild?.strategy !== "pure-agent" ? (
                  <span className="mt-1 block text-destructive/80">
                    The playable template version is still in My Creations — run the build again to retry the AI version.
                  </span>
                ) : (
                  <span className="mt-1 block text-destructive/80">
                    Run the build again from this page to retry.
                  </span>
                )}
              </div>
            )}

            {phase === "done" && (
              <div className="mt-6 rounded-xl border border-primary/40 bg-gradient-to-br from-[oklch(0.72_0.27_340)] to-[oklch(0.65_0.25_295)] p-5">
                <p className="label-mono text-[10px] text-white/80">{activeBuild?.statusText ?? studio.status}</p>
                <h4 className="mt-1 font-display text-xl font-black text-white">
                  {builtGame?.title ?? studio.generatedPackage.title} 🎮
                </h4>
                <div className="mt-4 flex flex-wrap gap-3">
                  <button
                    onClick={() =>
                      navigate({
                        to: "/edit/$gameId",
                        params: { gameId: builtGame?.id ?? studio.generatedPackage.id ?? "latest" },
                      })
                    }
                    className="flex items-center gap-2 rounded-lg bg-black/40 px-4 py-2 text-xs font-bold uppercase tracking-wider text-white"
                  >
                    <Wand2 className="size-4" /> Edit Game
                  </button>
                  <button
                    onClick={() =>
                      navigate({
                        to: "/edit/$gameId",
                        params: { gameId: builtGame?.id ?? studio.generatedPackage.id ?? "latest" },
                      })
                    }
                    className="flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-xs font-bold uppercase tracking-wider text-black"
                  >
                    <Rocket className="size-4" /> Publish
                  </button>
                  <button
                    onClick={() =>
                      navigate({
                        to: "/play/$gameId",
                        params: {
                          gameId:
                            builtGame?.id ?? builtGame?.templateId ?? studio.generatedPackage.templateId ?? "flappy",
                        },
                      })
                    }
                    className="flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-xs font-bold uppercase tracking-wider text-black"
                  >
                    <Play className="size-4" /> Play
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
