import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { Rocket, Bot, Loader2, Check, Play, ArrowRight, BriefcaseBusiness, Wand2 } from "lucide-react";
import { useStudioContext } from "@/context/StudioContext";
import { api, clearAuthToken, prefetchAuthToken } from "@/lib/api";
import { findGameTemplate } from "@/lib/templates-loader";
import { engineOf, getThumbnailUrl, templateEmoji } from "@/lib/studio-meta";
import { sendTonGenerationPayment } from "@/lib/tonPayment";
import { getTonWallet } from "@/lib/tonWallet";
import { usePrivy } from "@privy-io/react-auth";
import { useSignRawHash } from "@privy-io/react-auth/extended-chains";
import { CreatePageSkeleton } from "@/components/studio/PageSkeletons";
import { CreateConsolePanel } from "@/components/studio/CreateConsolePanel";
import { KultLogo } from "@/components/studio/KultLogo";
import { useCreateChatFlow } from "@/hooks/useCreateChatFlow";
import { vibeIdeas } from "@/lib/createChatFlow";
import cyberpunkSuggestion from "@/assets/create-suggestion-cyberpunk.webp";
import farmSuggestion from "@/assets/create-suggestion-farm.webp";

export const Route = createFileRoute("/_app/create")({
  pendingComponent: CreatePageSkeleton,
  head: () => ({
    meta: [
      { title: "Create — Creator Studio" },
      {
        name: "description",
        content: "Describe your game in a prompt and let the agent build a playable version.",
      },
    ],
  }),
  component: Create,
});

const ideas: Array<{ icon: string; text: string; image?: string }> = [
  { icon: "🏙️", image: cyberpunkSuggestion, text: "A neon-cyberpunk parkour runner in Tokyo" },
  { icon: "🐾", image: farmSuggestion, text: "Cozy farm sim where animals talk back" },
  { icon: "🪐", text: "Voxel space pirate adventure" },
  { icon: "🐱", text: "Roguelike dungeon crawler with cats" },
  { icon: "🥋", text: "Tekken style martial arts fighter generated by the AI agent" },
];

const steps = [
  "Submitting prompt",
  "Writing game code",
  "Testing & repairing",
  "Playable build ready",
];
const PENDING_TON_GENERATION_PAYMENT_KEY = "kult-pending-ton-generation-payment";

const stageToStep: Record<string, number> = {
  "writing-code": 1,
  "editing-seed": 1,
  repairing: 2,
  "fixing-syntax": 2,
  "fixing-runtime": 2,
};

function Create() {
  const { studio, addCreatedGame, removeCreatedGame } = useStudioContext();
  const { user } = usePrivy();
  const { signRawHash } = useSignRawHash();
  const navigate = useNavigate();
  const [templateSeed, setTemplateSeed] = useState<any | null>(null);
  const chat = useCreateChatFlow({
    onPromptChange: (prompt) => studio.setPrompt(prompt),
  });
  const {
    messages,
    setMessages,
    chatStage,
    setChatStage,
    chatInput,
    setChatInput,
    gameRequest,
    setGameRequest,
    finalPrompt,
    setFinalPrompt,
    sendChat,
    chatPrompt,
    isThinking,
    freshChat,
  } = chat;
  const [generationNotice, setGenerationNotice] = useState("");
  const [generationNoticeKind, setGenerationNoticeKind] = useState<"info" | "payment" | "error">(
    "info",
  );
  const [isPaying, setIsPaying] = useState(false);
  const strategySectionRef = useRef<HTMLDivElement>(null);
  const noticeRef = useRef<HTMLDivElement>(null);

  // The build itself lives in studio state + localStorage (kult-active-build),
  // so it survives navigating away and full page refreshes. This page only
  // renders whatever build is active until the user cancels/dismisses it.
  const activeBuild = studio.activeBuild;
  const phase: "idle" | "building" | "done" | "failed" = activeBuild ? activeBuild.phase : "idle";
  const buildingStrategy = phase === "building" ? activeBuild!.strategy : null;
  const builtGame = activeBuild?.game ?? null;
  // Re-render once a second while building so the elapsed time and step list move
  // even between 5s job polls.
  const [, setTick] = useState(0);
  useEffect(() => {
    const templateId = sessionStorage.getItem("kult-create-template-id");
    if (templateId) {
      sessionStorage.removeItem("kult-create-template-id");
      void findGameTemplate(templateId).then((template) => {
        if (!template) return;
        setTemplateSeed(template);
        studio.setEngine(engineOf(template));
        studio.setSelectedId(template.id);
        const category = String(template.category ?? "arcade").toLowerCase();
        const basePrompt = `Create a game like ${template.name}. Keep the core ${category} template feel: ${template.mechanic}`;
        setGameRequest(basePrompt);
        setChatStage("vibe");
        setMessages([
          {
            role: "assistant",
            text: `${template.name} is selected as your template. Tell me what theme, characters, rules, or difficulty changes you want.`,
          },
          { role: "user", text: basePrompt },
        ]);
        studio.setPrompt(basePrompt);
      });
      return;
    }

    const remixPrompt = sessionStorage.getItem("kult-remix-prompt");
    if (remixPrompt) {
      sessionStorage.removeItem("kult-remix-prompt");
      setGameRequest(remixPrompt);
      setChatStage("vibe");
      setMessages([
        { role: "assistant", text: "Remix loaded. What theme or character swap do you want?" },
        { role: "user", text: remixPrompt },
      ]);
      studio.setPrompt(remixPrompt);
      return;
    }

    const heroPrompt = sessionStorage.getItem("kult-create-prompt");
    if (heroPrompt) {
      sessionStorage.removeItem("kult-create-prompt");
      studio.setPrompt(heroPrompt);
      setGameRequest(heroPrompt);
      setFinalPrompt(heroPrompt);
      setChatStage("ready");
      setMessages([
        { role: "assistant", text: "Hey there! What kind of game do you want to create?" },
        { role: "user", text: heroPrompt.split(".")[0] ?? heroPrompt },
        { role: "assistant", text: heroPrompt },
        {
          role: "assistant",
          text: "Plan ready! Choose Hybrid Mode or Pure Agent Strategy below to start building.",
        },
      ]);
    }
  }, [studio, setChatStage, setFinalPrompt, setGameRequest, setMessages]);

  useEffect(() => {
    if (chatStage !== "ready" || phase !== "idle") return;
    const timer = window.setTimeout(() => {
      strategySectionRef.current?.scrollIntoView({ behavior: "smooth", block: "center" });
    }, 80);
    return () => window.clearTimeout(timer);
  }, [chatStage, phase]);

  useEffect(() => {
    if (phase !== "building") return;
    const interval = setInterval(() => setTick((t) => t + 1), 1000);
    return () => clearInterval(interval);
  }, [phase]);

  const elapsedSec = activeBuild
    ? Math.max(0, Math.floor((Date.now() - activeBuild.startedAt) / 1000))
    : 0;
  const step =
    phase === "building" ? (stageToStep[activeBuild?.progressStage ?? ""] ?? 0) : steps.length - 1;

  const showNotice = (
    message: string,
    kind: "info" | "payment" | "error" = "info",
  ) => {
    setGenerationNotice(message);
    setGenerationNoticeKind(kind);
    requestAnimationFrame(() => {
      noticeRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  };

  useEffect(() => {
    if (phase !== "failed") return;
    const statusText = activeBuild?.statusText ?? studio.agentStatus ?? "";
    if (!statusText) return;
    if (/free game|TON|payment required|generate another/i.test(statusText)) {
      setGenerationNotice(statusText);
      setGenerationNoticeKind("payment");
    } else if (!generationNotice) {
      setGenerationNotice(statusText);
      setGenerationNoticeKind("error");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, activeBuild?.statusText]);

  const formatPaidGenerationNotice = (error: any) => {
    const data = error?.response?.data;
    const payment = data?.payment;
    const amount = payment?.amount ?? 1;
    const currency = payment?.currency ?? "TON";
    const existing = Number(payment?.existingGames ?? 0);
    const serverError = String(data?.error ?? "").trim();
    if (data?.code === "PAID_GENERATION_REQUIRED") {
      return (
        serverError ||
        `You've already created your free game${existing > 0 ? ` (${existing} so far)` : ""}. Pay ${amount} ${currency} to generate another.`
      );
    }
    return serverError || error?.message || "Could not start generation.";
  };

  const build = async (strategy: "pure-agent" | "hybrid", promptOverride = "") => {
    const pendingInput = chatInput.trim();
    const promptWithPendingInput = [finalPrompt || chatPrompt || studio.prompt, pendingInput]
      .filter(Boolean)
      .join(". ");
    const buildPrompt = promptOverride || promptWithPendingInput;
    if (!buildPrompt.trim() || phase === "building") return;
    setGenerationNotice("");
    setGenerationNoticeKind("info");
    try {
      const game = await studio.generateFromPrompt(strategy, buildPrompt);
      if (game) addCreatedGame(game);
    } catch (error: any) {
      const payment = error?.response?.data?.payment;
      const isPaidRequired =
        error?.response?.status === 402 &&
        (error?.response?.data?.code === "PAID_GENERATION_REQUIRED" || Boolean(payment?.required));

      if (isPaidRequired) {
        const amount = payment?.amount ?? 1;
        const currency = payment?.currency ?? "TON";
        showNotice(formatPaidGenerationNotice(error), "payment");
        try {
          const tonWallet = getTonWallet(user);
          if (!tonWallet) {
            showNotice(
              `${formatPaidGenerationNotice(error)} Connect your TON wallet in the header to continue.`,
              "payment",
            );
            return;
          }
          setIsPaying(true);
          let paymentTxHash = sessionStorage.getItem(PENDING_TON_GENERATION_PAYMENT_KEY) ?? "";
          if (!paymentTxHash) {
            showNotice(
              `Confirm ${amount} ${currency} in your wallet to unlock another game.`,
              "payment",
            );
            paymentTxHash = await sendTonGenerationPayment({
              wallet: tonWallet,
              amountTon: amount,
              signRawHash,
            });
            sessionStorage.setItem(PENDING_TON_GENERATION_PAYMENT_KEY, paymentTxHash);
          }
          showNotice("Payment sent. Verifying on TON mainnet…", "info");
          let game = null;
          for (let attempt = 1; attempt <= 2; attempt += 1) {
            try {
              game = await studio.generateFromPrompt(strategy, buildPrompt, paymentTxHash);
              break;
            } catch (verifyError: any) {
              const waitingForTon =
                verifyError?.response?.status === 402 &&
                verifyError?.response?.data?.code === "PAYMENT_NOT_CONFIRMED";
              if (!waitingForTon || attempt === 2) throw verifyError;
              showNotice("Payment sent. Waiting for TON confirmation…", "info");
              await new Promise((resolve) => setTimeout(resolve, 5000));
            }
          }
          if (game) addCreatedGame(game);
          sessionStorage.removeItem(PENDING_TON_GENERATION_PAYMENT_KEY);
          setGenerationNotice("");
          setGenerationNoticeKind("info");
        } catch (paymentError: any) {
          showNotice(
            paymentError?.response?.data?.error ??
              paymentError?.message ??
              `Could not complete ${currency} payment. Please try again.`,
            "error",
          );
        } finally {
          setIsPaying(false);
        }
      } else {
        const serverError = String(error?.response?.data?.error ?? error?.message ?? "").trim();
        if (error?.response?.status === 401 || /authorization token/i.test(serverError)) {
          clearAuthToken();
          void prefetchAuthToken();
          showNotice(
            "Sign in with TON Wallet in the header, then try building again.",
            "error",
          );
          return;
        }
        showNotice(formatPaidGenerationNotice(error), "error");
      }
    }
  };

  // Cancel a running build: stop polling, drop the persisted record, and delete
  // the already-saved game entry so nothing half-built lingers in My Creations.
  const cancelBuild = () => {
    const gameId = activeBuild?.game?.id;
    studio.cancelActiveBuild();
    if (phase === "building" && gameId) void removeCreatedGame(gameId);
  };

  const sendChatMessage = (text = chatInput) => {
    if (phase === "building") return;
    sendChat(text);
  };

  const submitComposerPrompt = () => {
    const value = chatInput.trim();
    if (phase === "building") return;

    if (chatStage === "game" || chatStage === "vibe" || chatStage === "concept") {
      if (!value) return;
      sendChatMessage(value);
      return;
    }

    const prompt = [finalPrompt || chatPrompt || studio.prompt, value].filter(Boolean).join(". ");
    if (!prompt.trim()) return;
    studio.setPrompt(prompt);
    setChatInput("");
    setMessages((current) => [
      ...current,
      ...(value ? [{ role: "user" as const, text: value }] : []),
      { role: "assistant", text: "Starting Hybrid Mode build…" },
    ]);
    void build("hybrid", prompt);
  };

  return (
    <div className="relative min-h-screen overflow-x-hidden text-white">
      <div className="relative z-10 mx-auto max-w-3xl px-4 pb-28 pt-2 sm:px-6 sm:pb-6 sm:pt-4">
        {generationNotice && (
          <div
            ref={noticeRef}
            role="alert"
            className={`mb-4 rounded-2xl border-2 px-4 py-3 text-sm font-black shadow-[0_8px_24px_rgba(124,58,237,0.25)] ${
              generationNoticeKind === "payment"
                ? "border-amber-300 bg-amber-50 text-amber-950"
                : generationNoticeKind === "error"
                  ? "border-rose-300 bg-rose-50 text-rose-950"
                  : "border-fuchsia-200 bg-white/90 text-violet-950"
            }`}
          >
            <p className="text-[10px] font-black uppercase tracking-[0.14em] opacity-70">
              {generationNoticeKind === "payment"
                ? "Payment required"
                : generationNoticeKind === "error"
                  ? "Build failed"
                  : "Notice"}
            </p>
            <p className="mt-1 leading-snug">{generationNotice}</p>
            {generationNoticeKind === "payment" && (
              <p className="mt-2 text-xs font-bold opacity-80">
                Your first game is free. Additional generations cost 1 TON.
              </p>
            )}
          </div>
        )}

        <header className="mb-4 flex items-center justify-between gap-3 sm:mb-5">
          <div className="flex min-w-0 items-center gap-3 rounded-[1.35rem] border-2 border-white/70 bg-white/82 px-3.5 py-2.5 text-violet-950 shadow-[0_0_22px_rgba(168,85,247,0.3),inset_0_2px_10px_rgba(255,255,255,0.95)] backdrop-blur sm:rounded-[1.6rem] sm:px-4 sm:py-3">
            <KultLogo className="h-7 w-auto max-w-[100px] object-contain sm:h-8 sm:max-w-[120px]" />
            <div>
              <p className="font-display text-xl font-black leading-none text-violet-900 sm:text-2xl">Create</p>
              <p className="text-[11px] font-bold text-violet-600 sm:text-xs">Describe it. AI builds it.</p>
            </div>
          </div>
          <span className="hidden shrink-0 items-center gap-2 rounded-[1.6rem] border-2 border-violet-300/60 bg-white/82 px-4 py-3 font-display text-sm font-black text-violet-800 shadow-[inset_0_2px_10px_rgba(255,255,255,0.9),0_0_18px_rgba(168,85,247,0.3)] backdrop-blur sm:inline-flex">
            <Bot className="size-6 text-violet-700" /> AI Game Studio
          </span>
        </header>

        {templateSeed && (
          <div className="mb-4 flex gap-2.5 rounded-[1.25rem] border-2 border-fuchsia-200 bg-white/85 p-2.5 text-violet-950 shadow-[0_0_16px_rgba(168,85,247,0.28)] backdrop-blur sm:gap-3 sm:rounded-[1.5rem] sm:p-3">
            <div className="relative size-12 shrink-0 overflow-hidden rounded-xl border border-violet-200 bg-violet-100 sm:size-16 sm:rounded-2xl">
              {getThumbnailUrl(templateSeed.id) ? (
                <img
                  src={getThumbnailUrl(templateSeed.id)}
                  alt=""
                  className="h-full w-full object-cover"
                />
              ) : (
                <span className="grid h-full place-items-center text-2xl sm:text-3xl">
                  {templateEmoji[templateSeed.id] ?? "🎮"}
                </span>
              )}
            </div>
            <div className="min-w-0 flex-1">
              <p className="text-[9px] font-black uppercase tracking-[0.16em] text-fuchsia-600 sm:text-[10px]">
                Template selected
              </p>
              <h2 className="truncate font-display text-base font-black sm:text-lg">{templateSeed.name}</h2>
              <p className="line-clamp-1 text-[11px] font-semibold text-violet-700 sm:line-clamp-2 sm:text-xs">
                {templateSeed.mechanic}
              </p>
            </div>
            <button
              type="button"
              onClick={() => navigate({ to: "/templates" })}
              className="self-center rounded-lg border border-violet-300 bg-white/80 px-2.5 py-1.5 text-[11px] font-black text-violet-700 sm:rounded-xl sm:px-3 sm:py-2 sm:text-xs"
            >
              Change
            </button>
          </div>
        )}

        <section className="mb-4 overflow-hidden rounded-[1.5rem] border-[3px] border-white/80 bg-[radial-gradient(circle_at_50%_5%,rgba(168,85,247,0.28),transparent_24%),linear-gradient(180deg,#160543,#070018)] p-3.5 shadow-[0_0_0_2px_rgba(168,85,247,0.5),0_0_36px_rgba(168,85,247,0.75),inset_0_1px_22px_rgba(255,255,255,0.12)] sm:rounded-[2rem] sm:border-[5px] sm:p-5">
          <div className="hidden flex-col items-center text-center sm:flex">
            <span className="relative grid size-20 place-items-center rounded-full border-2 border-fuchsia-200 bg-[radial-gradient(circle_at_35%_25%,#ffb7ff,#a855f7_48%,#3b0764_100%)] shadow-[0_0_26px_rgba(217,70,239,0.9)]">
              <Bot className="size-11 text-cyan-200 drop-shadow-[0_0_10px_rgba(103,232,249,0.95)]" />
            </span>
            <h1 className="mt-4 font-display text-4xl font-black">Hey there! 👋</h1>
            <p className="mt-1 text-base font-bold text-violet-200">
              What kind of game do you want to create?
            </p>
          </div>

          {freshChat ? (
            <div className="grid gap-2.5 sm:mt-5 sm:gap-3">
              <p className="text-center font-display text-xs font-black text-fuchsia-200 sm:text-sm">
                {templateSeed ? "Tell me how to remix it" : "Or try a starter idea"}
              </p>
              {ideas.slice(0, 2).map((idea) => (
                <button
                  key={idea.text}
                  onClick={() => sendChatMessage(idea.text)}
                  className="group flex items-center gap-2.5 rounded-[1.15rem] border border-fuchsia-300/45 bg-[linear-gradient(135deg,rgba(72,20,137,0.92),rgba(38,10,91,0.96))] p-2 text-left shadow-[0_0_14px_rgba(168,85,247,0.28),inset_0_1px_12px_rgba(255,255,255,0.08)] transition hover:border-fuchsia-200 sm:gap-3 sm:rounded-[1.35rem] sm:p-2.5"
                >
                  <span className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-xl border border-fuchsia-200/50 bg-[radial-gradient(circle,#c084fc,#4c1d95_74%)] text-xl shadow-[inset_0_2px_10px_rgba(255,255,255,0.22)] sm:size-16 sm:rounded-2xl sm:text-3xl">
                    {idea.image ? (
                      <img
                        src={idea.image}
                        alt=""
                        className="h-full w-full object-cover"
                        loading="lazy"
                      />
                    ) : (
                      idea.icon
                    )}
                  </span>
                  <span className="min-w-0 flex-1 text-[13px] font-black leading-tight text-white sm:text-lg">
                    {idea.text}
                  </span>
                  <ArrowRight className="size-5 shrink-0 text-fuchsia-300 transition group-hover:translate-x-1 sm:size-7" />
                </button>
              ))}
            </div>
          ) : (
            <>
              <div className="max-h-[32vh] space-y-2.5 overflow-y-auto pr-1 sm:mt-5 sm:max-h-[36vh] sm:space-y-3 [scrollbar-width:thin] [scrollbar-color:rgba(232,121,249,0.75)_transparent]">
                {messages.map((message, index) => (
                  <div
                    key={`${message.role}-${index}`}
                    className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}
                  >
                    <div
                      className={`max-w-[88%] rounded-2xl px-3.5 py-2.5 text-[13px] font-semibold leading-relaxed sm:px-4 sm:py-3 sm:text-sm ${
                        message.role === "user"
                          ? "bg-fuchsia-400/35 text-white"
                          : "bg-white/8 text-violet-100"
                      }`}
                    >
                      {message.text}
                    </div>
                  </div>
                ))}
              </div>
              <div className="mt-3 flex flex-wrap gap-1.5 sm:mt-4 sm:gap-2">
                {(chatStage === "game" ? ideas.map((i) => i.text) : vibeIdeas).map((idea) => (
                  <button
                    key={idea}
                    onClick={() => sendChatMessage(idea)}
                    className="rounded-full border border-fuchsia-300/40 bg-white/8 px-3 py-1.5 text-[11px] font-bold text-violet-100 transition hover:border-fuchsia-200 sm:px-4 sm:py-2 sm:text-xs"
                  >
                    {idea}
                  </button>
                ))}
                {chatStage === "concept" && (
                  <button
                    onClick={() => sendChatMessage("Ok, create it!")}
                    className="rounded-full bg-fuchsia-400 px-3 py-1.5 text-[11px] font-black text-white sm:px-4 sm:py-2 sm:text-xs"
                  >
                    Ok, create it!
                  </button>
                )}
              </div>
            </>
          )}
        </section>

        <div
          ref={strategySectionRef}
          className={`mb-4 grid gap-2 sm:grid-cols-2 ${freshChat ? "hidden sm:grid" : ""}`}
        >
          {chatStage === "ready" && phase === "idle" && (
            <p className="sm:col-span-2 rounded-xl border border-fuchsia-200/70 bg-white/85 px-3 py-2 text-center text-xs font-black text-violet-900 shadow-[0_0_20px_rgba(168,85,247,0.35)]">
              Prompt locked. Tap Hybrid Mode or Pure Agent to start building.
            </p>
          )}
          <button
            onClick={() => build("hybrid")}
            disabled={phase === "building" || isPaying || (!finalPrompt && !chatPrompt && !studio.prompt)}
            className="group relative flex items-center gap-2.5 overflow-hidden rounded-2xl border-2 border-fuchsia-200/80 bg-[linear-gradient(135deg,#a855f7,#6d28d9)] p-2.5 text-left shadow-[0_0_24px_rgba(168,85,247,0.65),inset_0_1px_16px_rgba(255,255,255,0.18)] disabled:opacity-60"
          >
            <span className="grid size-9 shrink-0 place-items-center rounded-full bg-white/20">
              <Bot className="size-5 text-cyan-200" />
            </span>
            <span className="min-w-0 flex-1">
              <span className="block font-display text-sm font-black text-white">HYBRID MODE</span>
              <span className="block truncate text-[11px] font-bold text-violet-100">
                {isPaying
                  ? "Waiting for payment..."
                  : buildingStrategy === "hybrid"
                    ? "Building your game..."
                    : "Best of both worlds."}
              </span>
            </span>
            <span className="grid size-7 shrink-0 place-items-center rounded-full border border-white/35 bg-white/12 text-white">
              {buildingStrategy === "hybrid" || isPaying ? (
                <Loader2 className="size-3.5 animate-spin" />
              ) : (
                <ArrowRight className="size-4" />
              )}
            </span>
          </button>

          <button
            onClick={() => build("pure-agent")}
            disabled={phase === "building" || isPaying || (!finalPrompt && !chatPrompt && !studio.prompt)}
            className="group flex items-center gap-2.5 rounded-2xl border-2 border-fuchsia-200/80 bg-[linear-gradient(135deg,#ec4899,#7e22ce)] p-2.5 text-left shadow-[0_0_24px_rgba(236,72,153,0.5),inset_0_1px_16px_rgba(255,255,255,0.18)] disabled:opacity-60"
          >
            <span className="grid size-9 shrink-0 place-items-center rounded-full bg-white/20">
              <BriefcaseBusiness className="size-4.5 text-pink-100" />
            </span>
            <span className="min-w-0 flex-1">
              <span className="block font-display text-sm font-black text-white">PURE AGENT</span>
              <span className="block truncate text-[11px] font-bold text-pink-100">
                {isPaying
                  ? "Waiting for payment..."
                  : buildingStrategy === "pure-agent"
                    ? "Building your game..."
                    : "AI handles everything."}
              </span>
            </span>
            <span className="grid size-7 shrink-0 place-items-center rounded-full border border-white/35 bg-white/12 text-white">
              {buildingStrategy === "pure-agent" || isPaying ? (
                <Loader2 className="size-3.5 animate-spin" />
              ) : (
                <ArrowRight className="size-4" />
              )}
            </span>
          </button>
        </div>

        <div className="mb-4 w-full">
          <div className="relative overflow-hidden rounded-[1.35rem] border-2 border-fuchsia-300/70 bg-[linear-gradient(160deg,#16082f_0%,#0a0118_55%,#1a0a3e_100%)] p-3 shadow-[0_0_0_1px_rgba(244,114,182,0.35),0_0_32px_rgba(168,85,247,0.45),inset_0_1px_16px_rgba(255,255,255,0.08)] sm:rounded-[1.5rem] sm:p-4">
            <div className="pointer-events-none absolute -right-8 -top-8 size-28 rounded-full bg-fuchsia-500/20 blur-3xl" />
            <p className="relative mb-2 text-center font-display text-[10px] font-black uppercase tracking-[0.14em] text-fuchsia-300">
              {templateSeed ? "Describe your remix" : "Type your game idea"}
            </p>
            <CreateConsolePanel
              value={chatInput}
              onChange={setChatInput}
              onSubmit={submitComposerPrompt}
              onCategoryPick={(seed) => {
                if (chatStage === "game" || chatStage === "vibe" || chatStage === "concept") {
                  sendChatMessage(seed);
                }
              }}
              disabled={phase === "building" || isThinking}
              placeholder={
                chatStage === "game" ? "Type your game idea here…" : "Type a prompt…"
              }
              className="relative !rounded-[1.1rem] !border-2 !border-fuchsia-400/80 !bg-[#12082a]/95 !p-2.5 !shadow-[0_0_22px_rgba(217,70,239,0.45),inset_0_1px_10px_rgba(255,255,255,0.08)] sm:!p-3"
            />
          </div>
        </div>

        {phase !== "idle" && (
          <div className="animate-float-up mt-6 rounded-[1.75rem] border-2 border-fuchsia-200/80 bg-white/95 p-5 text-violet-950 shadow-[0_12px_32px_rgba(124,58,237,0.22)] sm:p-6">
            <div className="flex items-start justify-between gap-3">
              <div className="min-w-0">
                <h3 className="truncate font-display text-xl font-black sm:text-2xl">
                  {builtGame?.title ?? "Build Console"}
                </h3>
                <p className="mt-1 text-[10px] font-black uppercase tracking-[0.16em] text-violet-500">
                  {phase === "done"
                    ? "AI Build Ready"
                    : phase === "failed"
                      ? "Build Failed"
                      : activeBuild?.statusText ?? studio.agentStatus}
                  {phase === "building"
                    ? ` · ${Math.floor(elapsedSec / 60)}m ${elapsedSec % 60}s`
                    : ""}
                </p>
              </div>
              {phase === "building" ? (
                <button
                  onClick={cancelBuild}
                  className="shrink-0 rounded-full border border-rose-300/70 px-3 py-1.5 text-[11px] font-black uppercase tracking-wider text-rose-600 transition hover:bg-rose-50"
                >
                  Cancel
                </button>
              ) : (
                <button
                  onClick={cancelBuild}
                  className="shrink-0 rounded-full border border-violet-200 px-3 py-1.5 text-[11px] font-black uppercase tracking-wider text-violet-600 transition hover:bg-violet-50"
                >
                  Dismiss
                </button>
              )}
            </div>
            <ul className="mt-4 space-y-3">
              {steps.map((s, i) => {
                const active = phase === "building" && i === step;
                const complete = phase === "done" || phase === "failed" || i < step;
                return (
                  <li key={s} className="flex items-center gap-3 text-sm font-semibold">
                    <span className="flex size-6 items-center justify-center rounded-full border border-violet-200 bg-violet-50">
                      {complete ? (
                        <Check className="size-3.5 text-emerald-500" />
                      ) : active ? (
                        <Loader2 className="size-3.5 animate-spin text-fuchsia-500" />
                      ) : (
                        <span className="size-1.5 rounded-full bg-violet-300" />
                      )}
                    </span>
                    <span className={complete || active ? "text-violet-950" : "text-violet-400"}>
                      {s}
                    </span>
                  </li>
                );
              })}
            </ul>

            {phase === "failed" && (
              <div className="mt-6 rounded-xl border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
                {activeBuild?.statusText ?? "The AI build failed."}
                {builtGame?.id && activeBuild?.strategy !== "pure-agent" ? (
                  <span className="mt-1 block text-destructive/80">
                    The playable template version is still in My Creations — run the build again to
                    retry the AI version.
                  </span>
                ) : (
                  <span className="mt-1 block text-destructive/80">
                    Run the build again from this page to retry.
                  </span>
                )}
              </div>
            )}

            {phase === "done" && (
              <div className="mt-6 rounded-xl border border-primary/40 bg-gradient-to-br from-[oklch(0.72_0.27_340)] to-[oklch(0.65_0.25_295)] p-5">
                <p className="label-mono text-[10px] text-white/80">
                  {activeBuild?.statusText ?? studio.status}
                </p>
                <h4 className="mt-1 font-display text-xl font-black text-white">
                  {builtGame?.title ?? studio.generatedPackage.title} 🎮
                </h4>
                <div className="mt-4 flex flex-wrap gap-3">
                  <button
                    onClick={() =>
                      navigate({
                        to: "/edit/$gameId",
                        params: { gameId: builtGame?.id ?? studio.generatedPackage.id ?? "latest" },
                      })
                    }
                    className="flex items-center gap-2 rounded-lg bg-black/40 px-4 py-2 text-xs font-bold uppercase tracking-wider text-white"
                  >
                    <Wand2 className="size-4" /> Edit Game
                  </button>
                  <button
                    onClick={() =>
                      navigate({
                        to: "/edit/$gameId",
                        params: { gameId: builtGame?.id ?? studio.generatedPackage.id ?? "latest" },
                      })
                    }
                    className="flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-xs font-bold uppercase tracking-wider text-black"
                  >
                    <Rocket className="size-4" /> Publish
                  </button>
                  <button
                    onClick={() =>
                      navigate({
                        to: "/play/$gameId",
                        params: {
                          gameId:
                            builtGame?.id ??
                            builtGame?.templateId ??
                            studio.generatedPackage.templateId ??
                            "flappy",
                        },
                      })
                    }
                    className="flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-xs font-bold uppercase tracking-wider text-black"
                  >
                    <Play className="size-4" /> Play
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
