/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMoreRouteImport } from './routes/_app.more'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppPlayGameIdRouteImport } from './routes/_app.play.$gameId'
import { Route as AppEditGameIdRouteImport } from './routes/_app.edit.$gameId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayGameIdRoute = AppPlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const AppEditGameIdRoute = AppEditGameIdRouteImport.update({
  id: '/edit/$gameId',
  path: '/edit/$gameId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/create': typeof AppCreateRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/more': typeof AppMoreRoute
  '/profile': typeof AppProfileRoute
  '/templates': typeof AppTemplatesRoute
  '/edit/$gameId': typeof AppEditGameIdRoute
  '/play/$gameId': typeof AppPlayGameIdRoute
}
export interface FileRoutesByTo {
  '/create': typeof AppCreateRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/more': typeof AppMoreRoute
  '/profile': typeof AppProfileRoute
  '/templates': typeof AppTemplatesRoute
  '/': typeof AppIndexRoute
  '/edit/$gameId': typeof AppEditGameIdRoute
  '/play/$gameId': typeof AppPlayGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/create': typeof AppCreateRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/edit/$gameId': typeof AppEditGameIdRoute
  '/_app/play/$gameId': typeof AppPlayGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/leaderboard'
    | '/more'
    | '/profile'
    | '/templates'
    | '/edit/$gameId'
    | '/play/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create'
    | '/leaderboard'
    | '/more'
    | '/profile'
    | '/templates'
    | '/'
    | '/edit/$gameId'
    | '/play/$gameId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/create'
    | '/_app/leaderboard'
    | '/_app/more'
    | '/_app/profile'
    | '/_app/templates'
    | '/_app/'
    | '/_app/edit/$gameId'
    | '/_app/play/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/$gameId': {
      id: '/_app/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof AppPlayGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/edit/$gameId': {
      id: '/_app/edit/$gameId'
      path: '/edit/$gameId'
      fullPath: '/edit/$gameId'
      preLoaderRoute: typeof AppEditGameIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMoreRoute: typeof AppMoreRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEditGameIdRoute: typeof AppEditGameIdRoute
  AppPlayGameIdRoute: typeof AppPlayGameIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMoreRoute: AppMoreRoute,
  AppProfileRoute: AppProfileRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppEditGameIdRoute: AppEditGameIdRoute,
  AppPlayGameIdRoute: AppPlayGameIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
