/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlayRouteImport } from './routes/_app.play'
import { Route as AppMoreRouteImport } from './routes/_app.more'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppPlayGameIdRouteImport } from './routes/_app.play.$gameId'
import { Route as AppEditGameIdRouteImport } from './routes/_app.edit.$gameId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayGameIdRoute = AppPlayGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppEditGameIdRoute = AppEditGameIdRouteImport.update({
  id: '/edit/$gameId',
  path: '/edit/$gameId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/more': typeof AppMoreRoute
  '/play': typeof AppPlayRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/templates': typeof AppTemplatesRoute
  '/edit/$gameId': typeof AppEditGameIdRoute
  '/play/$gameId': typeof AppPlayGameIdRoute
}
export interface FileRoutesByTo {
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/more': typeof AppMoreRoute
  '/play': typeof AppPlayRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/templates': typeof AppTemplatesRoute
  '/': typeof AppIndexRoute
  '/edit/$gameId': typeof AppEditGameIdRoute
  '/play/$gameId': typeof AppPlayGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/create': typeof AppCreateRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/play': typeof AppPlayRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/edit/$gameId': typeof AppEditGameIdRoute
  '/_app/play/$gameId': typeof AppPlayGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/leaderboard'
    | '/more'
    | '/play'
    | '/profile'
    | '/search'
    | '/templates'
    | '/edit/$gameId'
    | '/play/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create'
    | '/dashboard'
    | '/leaderboard'
    | '/more'
    | '/play'
    | '/profile'
    | '/search'
    | '/templates'
    | '/'
    | '/edit/$gameId'
    | '/play/$gameId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/create'
    | '/_app/dashboard'
    | '/_app/leaderboard'
    | '/_app/more'
    | '/_app/play'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/templates'
    | '/_app/'
    | '/_app/edit/$gameId'
    | '/_app/play/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/$gameId': {
      id: '/_app/play/$gameId'
      path: '/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof AppPlayGameIdRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/edit/$gameId': {
      id: '/_app/edit/$gameId'
      path: '/edit/$gameId'
      fullPath: '/edit/$gameId'
      preLoaderRoute: typeof AppEditGameIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPlayRouteChildren {
  AppPlayGameIdRoute: typeof AppPlayGameIdRoute
}

const AppPlayRouteChildren: AppPlayRouteChildren = {
  AppPlayGameIdRoute: AppPlayGameIdRoute,
}

const AppPlayRouteWithChildren =
  AppPlayRoute._addFileChildren(AppPlayRouteChildren)

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMoreRoute: typeof AppMoreRoute
  AppPlayRoute: typeof AppPlayRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEditGameIdRoute: typeof AppEditGameIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMoreRoute: AppMoreRoute,
  AppPlayRoute: AppPlayRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppEditGameIdRoute: AppEditGameIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
